package com.saga.choreography.dto;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents an order in the system
 * Used by:
 * - Order Service: Creates and stores this
 * - Payment Service: Reads totalAmount for payment
 * - Inventory Service: Reads items for stock reservation
 * - Notification Service: Reads order details for email
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderDTO {

    /**
     * Unique order ID (generated by order service)
     */
    private String orderId;

    /**
     * Customer ID from customer service
     */
    @NotNull(message = "Customer ID is required")
    private Long customerId;

    /**
     * Customer email for notifications
     */
    @Email(message = "Invalid email format")
    private String customerEmail;

    /**
     * Customer phone number for SMS
     */
    private String customerPhone;

    /**
     * List of items in the order
     */
    @NotEmpty(message = "Order must contain at least one item")
    private List<OrderItem> items;

    /**
     * Total amount (calculated by summing item prices)
     */
    private BigDecimal totalAmount;

    /**
     * Currency code (USD, EUR, etc.)
     */
    @Pattern(regexp = "^[A-Z]{3}$", message = "Currency must be 3-letter code")
    private String currency;

    /**
     * Current order status (PENDING, CONFIRMED, CANCELLED, etc.)
     */
    private String status;

    /**
     * Payment method (CREDIT_CARD, PAYPAL, BANK_TRANSFER)
     */
    private String paymentMethod;

    /**
     * When the order was created
     */
    private LocalDateTime createdAt;

    /**
     * When the order was last updated
     */
    private LocalDateTime updatedAt;

    /**
     * Shipping address for delivery
     */
    private ShippingAddress shippingAddress;

    /**
     * Special delivery instructions
     */
    private String deliveryNotes;

    // ========================================================================
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class OrderItem {
        /**
         * Product ID from catalog service
         */
        @NotNull(message = "Product ID is required")
        private Long productId;

        /**
         * Product name (for display)
         */
        private String productName;

        /**
         * Quantity ordered
         */
        @Min(value = 1, message = "Quantity must be at least 1")
        @Max(value = 999, message = "Quantity cannot exceed 999")
        private Integer quantity;

        /**
         * Price per unit at time of order
         */
        @Positive(message = "Unit price must be positive")
        private BigDecimal unitPrice;

        /**
         * Total price for this item (quantity * unitPrice)
         */
        private BigDecimal subtotal;
    }

    // ========================================================================
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ShippingAddress {
        private String street;
        private String city;
        private String state;
        private String postalCode;
        private String country;
    }
}