package com.saga.choreography.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a payment transaction
 * Used by:
 * - Payment Service: Processes and stores this
 * - Order Service: Reads payment status
 * - Notification Service: Includes payment details in receipts
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentDTO {

    /**
     * Unique payment ID (generated by payment service)
     */
    private String paymentId;

    /**
     * Order ID this payment belongs to
     */
    @NotNull(message = "Order ID is required")
    private String orderId;

    /**
     * Customer ID who made the payment
     */
    private Long customerId;

    /**
     * Amount to charge
     */
    @Positive(message = "Payment amount must be positive")
    private BigDecimal amount;

    /**
     * Currency code
     */
    private String currency;

    /**
     * Payment method (CREDIT_CARD, PAYPAL, etc.)
     */
    @NotBlank(message = "Payment method is required")
    private String paymentMethod;

    /**
     * Last 4 digits of card (if credit card)
     */
    @Pattern(regexp = "^\\d{4}$", message = "Must be 4 digits")
    private String cardLast4;

    /**
     * Card brand (VISA, MASTERCARD, AMEX)
     */
    private String cardBrand;

    /**
     * Payment gateway transaction ID (Stripe, PayPal, etc.)
     */
    private String transactionId;

    /**
     * Payment status (PENDING, COMPLETED, FAILED, REFUNDED)
     */
    private String status;

    /**
     * Failure reason (if payment failed)
     */
    private String failureReason;

    /**
     * When payment was processed
     */
    private LocalDateTime processedAt;

    /**
     * When payment was refunded (if applicable)
     */
    private LocalDateTime refundedAt;

    /**
     * Billing address for receipt
     */
    private BillingAddress billingAddress;

    // ========================================================================
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class BillingAddress {
        private String fullName;
        private String street;
        private String city;
        private String postalCode;
        private String country;
    }
}